# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FCNetworkingDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'AFNetworking'
  # Pods for FCNetworkingDemo

  target 'FCNetworkingDemoTests' do
    inherit! :search_paths
    # Pods for testing
pod 'AFNetworking'
  end

  target 'FCNetworkingDemoUITests' do
    inherit! :search_paths
    # Pods for testing
pod 'AFNetworking'
  end

end
